services:
  frontend:
    build:
      context: ./client
    image: monapp-frontend
    #ports:
    #  - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=/film-booking/
      - VITE_API_URL=http://backend:3000
    labels:
       - "traefik.enable=true"
#       - "traefik.http.routers.frontend.rule=Host(`srvdkpocprod.franceagrimer.fr`)"
       - "traefik.http.routers.frontend.rule=PathPrefix(`/film-booking`)"
       - "traefik.http.routers.frontend.middlewares=frontend-middle"
       - "traefik.http.middlewares.frontend-middle.stripprefix.prefixes=/film-booking"
#       - "traefik.http.routers.frontend.entrypoints=websecure"
       - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - traefik-network

  backend:
    build:
      context: ./server
    image: monapp-backend
    #ports:
    #  - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - JWT_SECRET=sfhbkjhrfbser
    networks:
      - traefik-network
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    #ports:
    #  - "5432:5432"
    networks:
      - traefik-network

volumes:
  pgdata:

networks:
  traefik-network:
    name: traefik-network
    external: true
