services:
  frontend:
    build:
      context: ./client
      args: 
        - VITE_API_BASE=/film-booking/
        - VITE_API_URL=api
    image: monapp-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - proxy-net

  backend:
    build:
      context: ./server
    image: monapp-backend
    #ports:
    #  - "3000:3000"
    depends_on:
      - db
    env_file: "./server/.env"
    networks:
      - proxy-net
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    networks:
      - proxy-net

volumes:
  pgdata:

networks:
  proxy-net:
    name: proxy-net
    external: true